
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS father_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS marital_status text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS religion text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS education text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS workplace_address text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS passport_number text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS email text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS emergency_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS emergency_relation text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS emergency_address text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS emergency_phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS domestic_worker_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS domestic_worker_nid text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS domestic_worker_phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS domestic_worker_address text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS driver_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS driver_nid text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS driver_phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS driver_address text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS prev_landlord_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS prev_landlord_phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS prev_landlord_address text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS prev_leave_reason text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS current_landlord_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS current_landlord_phone text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS living_since text NOT NULL DEFAULT '';
