// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djspxvtoxysjivhzrnuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqc3B4dnRveHlzaml2aHpybnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzQ5MDEsImV4cCI6MjA5MDQ1MDkwMX0.1UYwKe3QD3RUHap20kUcGHx4PbDqvMFhlnNC8XdH60c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});